### ISSUE TITLE
Other Files

### ISSUE THREAD

**Issue by xooxo** [474172261/wctf_vm_escape_virtualHole#1]
Hey,

Thanks for the challenge! I would like to take a look and try to solve it myself. But it seems that some files are missing :( 

Could you upload configure and virtual machine?

**Comment by 474172261** [comment]
you don't need any special configuration, you should compile qemu from source(as I said in readme), and then install a centos7 guest(other linux guest is also ok) by your self. Guest image is too big, github limits nearly 200Mb file size, so I can't upload it.
